   

name: Sync to S3
on:
  push:
    branches:
      - production
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  
    
    - name: Remove old files 
      run: aws s3 rm ${{ secrets.AWS_S3_BUCKET }} --recursive
    
    - name: Sync to S3
      run: aws s3 sync . ${{ secrets.AWS_S3_BUCKET }} --delete

    - name: Clean CloudFront Cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
    
    
